version: '3.9'

services:
  database:
    container_name: infant
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: infant_db
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      #- ./dump/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      #- ./dump/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    ports:
      - 5432:5432
    networks:
      - postgres
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: infantbeaver
    restart: always
    ports:
      - 8978:8978
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    environment:
      HTTP_PROXY: http://localhost:8978
      HTTPS_PROXY: http://localhost:8978
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data: {}
  cloudbeaver:
